name: stow_plain
description: Custom implementation of stow_codecs for OpenHarmony compatibility
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
      ref: br_shared_preferences-v2.3.2_ohos

  stow:
    path: ../stow
  stow_codecs:
    path: ../stow_codecs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
