name: saber
description: A cross-platform libre notes app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.26.8+26080

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  event_bus: ^2.0.1
  logger: ^2.6.0

  material_symbols_icons: ^4.2758.0

  dynamic_color:
    path: packages/dynamic_color

  flutter_staggered_grid_view: ^0.7.0

  go_router: ^15.1.2
  path_to_regexp: ^0.4.0

  perfect_freehand: ^2.2.1

  shared_preferences:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
      ref: br_shared_preferences-v2.3.2_ohos

  flutter_secure_storage: ^9.2.2

  # TODO
#  flutter_secure_storage_ohos:
#    git:
#      url: https://gitcode.com/openharmony-sig/fluttertpc_flutter_secure_storage.git
#      path: flutter_secure_storage_ohos

  url_launcher:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/url_launcher/url_launcher"

  nextcloud: ^8.1.0

  collapsible: ^1.0.0

  vector_math: ^2.2.0

  intl: any

  crypto: ^3.0.2
  encrypt: ^5.0.1

  http: ^1.1.0


  pdf: ^3.8.4

  share_plus:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/share_plus/share_plus

  # TODO
  file_picker: ^8.3.2
#  file_picker_ohos:
#    git:
#      url: https://gitcode.com/openharmony-sig/fluttertpc_file_picker.git
#      path: ohos

  regexed_validator: ^2.0.0+1

  slang: ^4.1.0
  slang_flutter:

  flex_color_picker:
    path: packages/flex_color_picker

  font_awesome_flutter:
    path: packages/font_awesome_flutter

  flutter_svg: ^2.0.0+1

  defer_pointer: ^0.0.2

  permission_handler:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_permission_handler.git"
      path: "permission_handler"

  saver_gallery: ^4.0.1

  animations: ^2.0.7

  flutter_quill:
    path: packages/flutter_quill

  worker_manager: ^7.0.1
  # 还没有 ohos 的支持 TODO
  workmanager:

  archive: ^4.0.3

  receive_sharing_intent: ^1.6.7

  # TODO
  #  receive_sharing_intent:
  #    git:
  #      url: "https://gitcode.com/openharmony-sig/fluttertpc_receive_sharing_intent.git"

  screenshot: ^3.0.0

  path_drawing: ^1.0.1

  printing:
    git:
      url: https://gitcode.com/openharmony-sig/fluttertpc_printing.git
      path: printing

  package_info_plus:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_plus_plugins.git"
      path: "packages/package_info_plus/package_info_plus"

# TODO
  open_file: ^3.5.10
#  open_file_ohos:
#    git:
#      url: https://gitcode.com/openharmony-sig/fluttertpc_open_file.git
#      path: "ohos"

  super_clipboard:
    path: packages/super_native_extensions/super_clipboard

  fast_image_resizer: ^0.0.2

  bson: ^5.0.0

  flutter_speed_dial: ^7.0.0

  logging: ^1.2.0

  fixnum: ^1.1.0

  device_info_plus:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/device_info_plus/device_info_plus

  one_dollar_unistroke_recognizer: ^1.1.1


  mutex: ^3.1.0

  collection: ^1.0.0

  audioplayers:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_audioplayers.git"
      path: "packages/audioplayers"
      ref: br_audioplayers-v6.1.0_ohos

  abstract_sync: ^1.3.0

  args: ^2.5.0

  flutter_web_auth_2: ^4.0.0

  path: ^1.9.0
  keybinder: ^1.0.1

  # 使用本地包
  pdfrx:
    path: packages/pdfrx

  stack_trace: ^1.11.1

  # TODO 这个依赖无用
  smooth_corner: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # integration_test:  # 暂时移除以避免 vector_math 版本冲突
  #   sdk: flutter

#  receive_sharing_intent_ohos:
#    git:
#      url: "https://gitcode.com/openharmony-sig/fluttertpc_receive_sharing_intent.git"
#      path: ./ohos

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

  icons_launcher: ^3.0.0

  simplytranslate: ^2.0.1

  yaml: ^3.1.2

  # golden_screenshot: ^4.0.0


dependency_overrides:
  # 统一 path_provider 的 ref，解决 audioplayers 和 share_plus 的冲突
  # 注意：audioplayers 和 share_plus 可能依赖不同仓库的 path_provider
  # 这里强制使用 openharmony-sig 的版本（与 audioplayers/share_plus 同组织）
  path_provider:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"
      ref: master
  
  # 同时统一平台实现
#  path_provider_android:
#    git:
#      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
#      path: "packages/path_provider/path_provider_android"
#      ref: master
  
  # 强制使用 Git 版本的 url_launcher（解决 flutter_web_auth_2 冲突）
  url_launcher:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/url_launcher/url_launcher"

  # 强制使用新版本的 http
  http: ^1.1.0

  uuid: ^4.1.0

  # 强制使用新版本的 mime
  mime: ^2.0.0

  file: ^7.0.0

  quill_native_bridge_windows: 0.0.1

  # 强制使用新版本的 vector_math
  vector_math: ^2.2.0
  
  # https://github.com/KasemJaffer/receive_sharing_intent/pull/333
#  receive_sharing_intent:
#    git:
#      url: https://github.com/KasemJaffer/receive_sharing_intent
#      ref: 2cea396843cd3ab1b5ec4334be4233864637874e

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon/icon.svg
    - assets/images/
    - assets/google_fonts/Atkinson_Hyperlegible_Next/OFL.txt
    - assets/google_fonts/Dekko/OFL.txt
    - assets/google_fonts/Fira_Mono/OFL.txt
    - assets/google_fonts/Neucha/OFL.txt
    - assets/audio/
    - assets/data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: AtkinsonHyperlegibleNext
      fonts:
        - asset: assets/google_fonts/Atkinson_Hyperlegible_Next/AtkinsonHyperlegibleNext-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Atkinson_Hyperlegible_Next/AtkinsonHyperlegibleNext-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/google_fonts/Atkinson_Hyperlegible_Next/AtkinsonHyperlegibleNext-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Atkinson_Hyperlegible_Next/AtkinsonHyperlegibleNext-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/google_fonts/Atkinson_Hyperlegible_Next/AtkinsonHyperlegibleNext-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Atkinson_Hyperlegible_Next/AtkinsonHyperlegibleNext-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Dekko
      fonts:
        - asset: assets/google_fonts/Dekko/Dekko-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: assets/google_fonts/Fira_Mono/FiraMono-Regular.ttf
        - asset: assets/google_fonts/Fira_Mono/FiraMono-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Fira_Mono/FiraMono-Bold.ttf
          weight: 700
    - family: Neucha
      fonts:
        - asset: assets/google_fonts/Neucha/Neucha-Regular.ttf
    - family: HeiTi
      fonts:
        - asset: assets/fonts/HeiW3.otf
        - asset: assets/fonts/HeiW6.otf

  shaders:
    - shaders/pencil.frag


# ./scripts/generate_icons.sh
icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#ffc800"
      adaptive_foreground_image: "assets/icon/icon_maskable.png"
      adaptive_monochrome_image: "assets/icon/icon_monochrome.png"

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: saber
  org: saber-yf
