name: stow_secure
description: Custom implementation of stow_codecs for OpenHarmony compatibility
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  # TODO 替换 ohos 的版本
  flutter_secure_storage:

  stow:
    path: ../stow
  stow_codecs:
    path: ../stow_codecs

  mutex:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
